# This code is Generated by AI(Gemini)
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv("Chinese_Population_Total_Both Sexes_(Single_Year_Ages).csv",sep=",")

selected_year= "2020"
## Plot the graph
df = df.dropna(subset=[selected_year])
# 2. Set up the figure and axis
fig, ax = plt.subplots(figsize=(10, 12))

# 3. Create a horizontal bar plot for the year 2020
# Y-axis: Age, X-axis: Population for 2020
ax.barh(df["Age"], df[selected_year], color='skyblue', edgecolor='navy')

# 4. Configure labels and title
ax.set_xlabel('Population', fontsize=12)
ax.set_ylabel('Age', fontsize=10)
ax.set_title(f'Population Distribution for Year {selected_year} (Ages 0-100)', fontsize=14)

# 5. Fix X-axis limits and ticks (0 to 7 with 1e7 scaling index)
# 7 * 1e7 = 70,000,000 max limit
ax.set_xlim(0, 4e7)
ax.set_xticks([i * 1e7 for i in range(5)])
ax.set_xticklabels([f'{i}e7' for i in range(5)])

# Invert y-axis so age 0 is at the top (optional, standard for demographic views)
ax.invert_yaxis()

# Display the plot
plt.tight_layout()
plot_filename = f"China_Population_{selected_year}_Statistic_Single_Year_Age.pdf"
plt.savefig(plot_filename)
print(f"\nTable successfully saved to {plot_filename}")
