# Plot(Man:Women_in_Urban_Area_2020)
import pandas as pd
import matplotlib.pyplot as plt
# plot the graph
selected_area = "Rural"
selected_year = "1982"
df = pd.read_csv(f"Chinese_Population_{selected_area}_{selected_year}_Male:Female_(5-Year_Ages).csv")
df.columns = df.columns.str.strip()

# start here copied from "Create_Plot(for_5_year_age_group).py" generated by AI
df.fillna(0)
df.set_index("Age",inplace=True)
df = df.apply(pd.to_numeric, errors="coerce").fillna(0)

# scale the data to 1e7 (divide by 10,000,000)
df = df/1e7

fig, ax = plt.subplots(figsize=(10, 12))

# Horizontal bar plotting
df.plot(kind="barh", ax=ax, width=0.8, colormap="viridis")

# Formatting the graph
ax.set_title(f"{selected_year} Man and Women population in {selected_area} Area", fontsize=16, pad=15)
ax.set_xlabel("Population Value (in 10 millions)", fontsize=12)
ax.set_ylabel("Age Group", fontsize=12)

#Set Explicit Limits for the X axis form 0-6 (1e7)
ax.set_xlim(0,6)
# Invert y-axis so younger age groups (0-4) appear at the top
ax.invert_yaxis()

# Add legend and grid
ax.legend(title="Year", bbox_to_anchor=(1.05, 1), loc="upper left")
ax.grid(axis="x", linestyle="--", alpha=0.7)

plt.tight_layout()
plot_filename = f"China_{selected_area}_Population_{selected_year}_Man_VS_Women.pdf"
plt.savefig(plot_filename)
print(f"\nTable successfully saved to {plot_filename}")