# python 3
# filename: Table(1_years_old_and_Specific_Women_Age_Range_Population_Ratio)
# Authors: Betty Botian Zhang, bz2443@nyu.edu
# AI Assistant: Gemini
"""In this study, we are trying to measure the change of 
women's likelyhood of giving birth in one year when they
are at the age that is likely to give birth.
We intentionally use the data of people that was one years 
old when taking the population sensus. This is Because the 
number more acuratly measures the people that is born in one
 year. As a consequence, the result would be the ratio for 
 the year before population sensus.
Then, we assume that women are likely to give birth between
20 to 50 year old. As a result, we need to add up the 
women's population between 21 and 51 years old in the 
population sensus.
"""
# This code is write by my own. AI(Gemini) fixed the problem of not reading values on line ??. AI(Gemini) also helped me to merge tables.
import pandas as pd

#Set up conditions
selected_people = "Japanese"
selected_nation = "Japan"
women_selected_age_starts = 21
women_selected_age_ends = 51


## Create table for people that is 1 years old in each of the stastic year
#read file
input_filename = f"{selected_people} Population Original Data(from UN).csv"
df = pd.read_csv(input_filename,sep=",")

# Creates a check_order
def Check_Year_Order_keep_Value_from_latest_Source_Year(data):
    # Sort the "Year"
    def sort_year(year_str):
        year_str = str(year_str).strip()
        try:
            return int(year_str)
        except ValueError:
            return 999

    def sort_source_year(source_year_str):
        source_year_str = str(source_year_str).strip()
        try:
            return int(source_year_str)
        except ValueError:
            return 999

    data["Year_Sort"] = data["Year"].apply(sort_year)
    data["Source_Year_Sort"] = data["Source Year"].apply(sort_source_year)

    #Sort data by Year_Sort and Source_Year_Sort (descending for source year)
    data_fix = data.sort_values(by=["Year_Sort","Source_Year_Sort"],ascending=[True,False])

    #drop duplicate for the same Year and Area, keep the latest Source Year Data
    data_fix = data_fix.drop_duplicates(subset=["Year","Age"],keep="first")
    return data_fix

#create filter for 1 years old population
df_filtered_table1= df[(df["Sex"]=="Both Sexes")&(df["Age"]=="1")&(df["Area"]=="Total")].copy()

#Check data
df_filtered_table1_checked = Check_Year_Order_keep_Value_from_latest_Source_Year(df_filtered_table1)
# create Table 1
pivot_table_1= df_filtered_table1_checked.pivot_table(
    index="Year",columns="Age",values="Value"
)
"""
# Save the table to CSV form
output_filename_1 = f"{selected_nation} 1 Years Old in Population Sensus(Each Year).csv"
pivot_table_1.to_csv(output_filename_1)
print(f"\nSucessfully Save file {output_filename_1}")
"""
## Create table for women's age between selected age range for each of the stastic year.(Also, show sum in this table). 
df["Age"] = pd.to_numeric(df["Age"], errors = "coerce")
df_filtered_table2 = df[(df["Sex"]=="Female")&(df["Area"]=="Total")&(df["Age"]>women_selected_age_starts-1)&(df["Age"]<women_selected_age_ends+1)].copy()

#Check Data
df_filtered_table2_Checked =  Check_Year_Order_keep_Value_from_latest_Source_Year(df_filtered_table2)

# Create Table 2
pivot_table_2 = df_filtered_table2_Checked.pivot_table(
    index = "Year", columns="Age", values = "Value"
)

#print(pivot_table_2)
"""
#Save the table to CSV form
output_filename_2 = f"{selected_nation} Women population in ({women_selected_age_starts}-{women_selected_age_ends}) group(Each Year population sensus).csv"
pivot_table_2.to_csv(output_filename_2)
print(f"\nSucessfully Save file {output_filename_2}")
"""
# This part Generated by AI, and revised by me.
# Create Merged Table
# Reset index to make 'Year' a column for merging
t1_reset = pivot_table_1.reset_index()
t2_reset = pivot_table_2.reset_index()

# Merge using 'inner' to keep only matching years
merged_table = pd.merge(t1_reset, t2_reset, on='Year', how='inner')

# Set 'Year' back as the index of the new table
merged_table = merged_table.set_index('Year')

#start this part write by meself and revised by AI.
# Set Values for "Women in Age Range Population Sum" in merged_table
merged_table["Women in Age Range Population Sum"]= 0
# Put the women bwteen 21 to 51 into new data frame for Table 2
for num in range(women_selected_age_starts,women_selected_age_ends+1,1):
    if num in merged_table.columns:
        merged_table["Women in Age Range Population Sum"]+=merged_table[num].fillna(0).values

merged_table["Ratio"] = merged_table["1"]/merged_table["Women in Age Range Population Sum"]

output_filename_2 = f"{selected_nation} Merged Table.csv"
merged_table.to_csv(output_filename_2)
print(f"\nSucessfully Save file {output_filename_2}")

# shart this part write by my own
result_df = pd.read_csv(f"{selected_nation} Merged Table.csv",sep=",")
clean_df = result_df.dropna(axis=0)
#Create Table
result_pivot_table = clean_df.pivot_table(
    index="Year", values="Ratio"
)

# Set Result dataframe and table
output_filename_3 = f"{selected_nation} 1 year old and ({women_selected_age_starts}-{women_selected_age_ends}) Women Ratio(Each Year population sensus).csv"
result_pivot_table.to_csv(output_filename_3)
print(f"\nSucessfully Save file {output_filename_3}")
