# Python 3
# filename: Table(%_Population_in_City_selected_Year_selected_sex)
# Authors: Betty Botian Zhang, bz2443@nyu.edu
# AI Assistant: Gemini
# filename: Table(%_Population_in_City_selected_Year_selected_sex)
"""In this program, I filterned the data and find urban and total population.
Then I calculated urbinzation rate. I used pandas to extract the population 
information based on a selection of sex, year, and nation. In the project, 
I selected "Both Sexes" and "Japan" specifically. I run this code for each
year I selected start from 1950s.(I should really try loops to make it more
efficent).
"""
## Note: The code is mostly write by myself, but AI make some small changes to it. 
 
# This part of code is write by me.
# Import
import pandas as pd

# Set up conditions
selected_sex = "Both Sexes"
selected_year = "2020"
selected_nation = "Japan"
selected_people = "Japanese"

# Read file
df = pd.read_csv(f"{selected_people} Population Original Data(from UN).csv",sep=",")
df.columns = df.columns.str.strip()

# From AI(Gemini), the revision is here. 

for col in ["Sex", "Area", "Year"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

#This part write by myself
# Create filter
df_filtered = df[(df["Year"]==selected_year)&(df["Sex"]==selected_sex)&(df["Area"].isin(["Urban","Total"]))&(df["Age"].astype(str).str.contains(r" - |\+", regex=True))].copy()

# This part revised by AI.
# check and make population numeric
value_col = "Value" if "Value" in df_filtered.columns else df_filtered.columns[-1]
df_filtered[value_col] = pd.to_numeric(df_filtered[value_col],errors="coerce")

#This part write by myself, but I learn the structure from AI.
# Sort the "Year" "Source Year"
def sort_age_ranges(age_str):
    age_str = str(age_str).strip()
    if " - " in age_str:
        try:
            return int(age_str.split(" - ")[0])
        except ValueError:
                    return 999
    elif "+" in age_str:
        try:
            return int(age_str.strip("+"))
        except ValueError:
            return 999
    return 999

def sort_source_year(source_year_str):
    source_year_str = str(source_year_str).strip()
    try:
        return int(source_year_str)
    except ValueError:
        return 999

df_filtered["Age_Sort"] = df_filtered["Age"].apply(sort_age_ranges)
df_filtered["Source_Year_Sort"] = df_filtered["Source Year"].apply(sort_source_year)

# This part generated by AI 
#Sort data by Year_Sort and Source_Year_Sort (descending for source year)
df_filtered = df_filtered.sort_values(by=["Age_Sort","Source_Year_Sort"],ascending=[True,False])

#drop duplicate for the same Year and Area, keep the latest Source Year Data
df_filtered = df_filtered.drop_duplicates(subset=["Age", "Area"],keep="first")
# create pivot table
pivot_df = df_filtered.pivot_table(
    index=["Age", "Age_Sort"],
    columns = "Area",
    values=value_col, 
    aggfunc="first"
).reset_index()

# Sort by year
pivot_df = pivot_df.sort_values("Age_Sort")

# create DataFrame
result_df = pd.DataFrame()
result_df["Age"] = pivot_df["Age"]

# set up values and calculations
urban_pop = pivot_df["Urban"] if "Urban" in pivot_df.columns else 0
total_pop = pivot_df["Total"] if "Total" in pivot_df.columns else 1

result_df["Urban_population"] = urban_pop
result_df["Total_population"] = total_pop
result_df["live_in_urban_percentage"] = result_df["Urban_population"]/result_df["Total_population"]

#This part write by myself.
# Create Table
file_name = f"{selected_nation}_Population_{selected_year}_{selected_sex}(%_live_in_Urban).csv"
result_df.to_csv(file_name,index=False)
print(f"successfully save to {file_name}")
